In [2]:
import numpy as np

In [3]:
def lin(x):
    return x + 1

In [4]:
d = [(1, 3), (1, 1), (3, 2), (3, 6)]

In [5]:
d[2]

(3, 2)

In [6]:
d[2][1]

2

In [7]:
[(d[i][1] - (d[i][0] + 1))**2 for i in range(len(d))]

[1, 1, 4, 4]

In [8]:
x = np.array([[d[i][0] for i in range(len(d))]])
x

array([[1, 1, 3, 3]])

In [9]:
y = np.array([[d[i][1] for i in range(len(d))]])

In [10]:
th_lue = np.array([[1]])

In [11]:
-2 * (np.dot(th_lue.T, x) - y) * x

array([[ 4,  0, -6, 18]])

In [12]:
np.dot(th_lue.T, x) * (-2)

array([[-2, -2, -6, -6]])

In [23]:
Z = np.array([[1, 2], [2, 3], [3, 5], [1, 4]])
Z

array([[1, 2],
       [2, 3],
       [3, 5],
       [1, 4]])

In [26]:
W = np.dot(Z, Z.T)
W

array([[ 5,  8, 13,  9],
       [ 8, 13, 21, 14],
       [13, 21, 34, 23],
       [ 9, 14, 23, 17]])

In [17]:
def lin_reg(x, th, th0):
    return np.dot(th.T, x) + th0

def square_loss(x, y, th, th0):
    return (y - lin_reg(x, th, th0))**2

def mean_square_loss(x, y, th, th0):
    # the axis=1 and keepdims=True are important when x is a full matrix
    return np.mean(square_loss(x, y, th, th0), axis = 1, keepdims = True)

In [20]:
X = np.array([[1., 2., 3., 4.], [1., 1., 1., 1.]])
Y = np.array([[1., 2.2, 2.8, 4.1]])
th = np.array([[1.0],[0.05]])
th0 = np.array([[0.]])

In [21]:
mean_square_loss(X, Y, th, th0)

array([[0.0225]])

In [22]:
# Write a function that returns the gradient of lin_reg(x, th, th0)
# with respect to th
def d_lin_reg_th(x, th, th0):
    return x

In [27]:
W[:-1, :]

array([[ 5,  8, 13,  9],
       [ 8, 13, 21, 14],
       [13, 21, 34, 23]])

In [28]:
W[-1:, :]

array([[ 9, 14, 23, 17]])

In [30]:
np.random.randint(10)

2

In [31]:
def downwards_line():
    X = np.array([[0.0, 0.1, 0.2, 0.3, 0.42, 0.52, 0.72, 0.78, 0.84, 1.0],
                  [1.0, 1.0, 1.0, 1.0, 1.0,  1.0,  1.0,  1.0,  1.0,  1.0]])
    y = np.array([[0.4, 0.6, 1.2, 0.1, 0.22, -0.6, -1.5, -0.5, -0.5, 0.0]])
    return X, y

X, y = downwards_line()

def J(Xi, yi, w):
    # translate from (1-augmented X, y, theta) to (separated X, y, th, th0) format
    return float(ridge_obj(Xi[:-1,:], yi, w[:-1,:], w[-1:,:], 0))

def dJ(Xi, yi, w):
    def f(w): return J(Xi, yi, w)
    return num_grad(f)(w)

In [32]:
def num_grad(f):
    def df(x):
        g = np.zeros(x.shape)
        delta = 0.001
        for i in range(x.shape[0]):
            xi = x[i,0]
            x[i,0] = xi - delta
            xm = f(x)
            x[i,0] = xi + delta
            xp = f(x)
            x[i,0] = xi
            g[i,0] = (xp - xm)/(2*delta)
        return g
    return df

In [33]:
W[1,1]

13

In [35]:
W[:,1:2]

array([[ 8],
       [13],
       [21],
       [14]])

In [36]:
def sgd(X, y, J, dJ, w0, step_size_fn, max_iter):
    _, n = X.shape
    ws = [w0]
    fs = [] 
    for t in range(max_iter):
        w_old = ws[-1]
        # Picking a data among dataset randomly i.e. stochastic
        i = np.random.randint(n)
        xi = X[:, i:i+1]
        yi = y[:, i:i+1]
        # Updating weight
        w_new = w_old - step_size_fn(t) * dJ(xi, yi, w_old)
        ws.append(w_new)
        fs.append(J(xi, yi, w_new))
    return ws[-1], ws, fs