In [1]:
import numpy as np

In [2]:
x = np.array([[-3, 2], [-1, 1], [-1, -1], [2, 2], [1, -1]]).T
x

array([[-3, -1, -1,  2,  1],
       [ 2,  1, -1,  2, -1]])

In [3]:
d, n = x.shape
(d, n)

(2, 5)

In [4]:
y = np.array([[1, -1, -1, -1, -1]])
y

array([[ 1, -1, -1, -1, -1]])

In [5]:
y[0, 1]

-1

In [6]:
x[:, 0:1]

array([[-3],
       [ 2]])

In [7]:
th = np.zeros((d, 1))
th0 = np.zeros((1, 1))
for t in range(10):
    changed = False
    for i in range(n):
        if y[0, i] * (np.dot(th.T, x[:, i : i+1]) + th0[0, 0]) <= 0:
            th = th + y[0, i] * x[:, i : i+1]
            th0 = th0 + y[0, i]
            changed = True
    if not changed:
        break

In [8]:
th

array([[-2.],
       [ 0.]])

In [9]:
th0

array([[-5.]])

In [10]:
t

4

In [11]:
def perceptron(data, labels, params={}, hook=None):
    # if T not in params, default to 100
    T = params.get('T', 100)
    # Your implementation here
    d, n = data.shape
    th = np.zeros((d, 1))
    th0 = np.zeros((1, 1))

    for t in range(T):
        changed = False
        for i in range(n):
            if labels[0, i] * (np.dot(th.T, data[:, i : i+1]) + th0[0, 0]) <= 0:
                th = th + labels[0, i] * data[:, i : i+1]
                th0 = th0 + labels[0, i]
                changed = True
        if not changed:
            break
    return (th, th0)

In [12]:
perceptron(x, y, {'T': 100})

(array([[-2.],
        [ 0.]]),
 array([[-5.]]))

In [13]:
t

4

In [16]:
def averaged_perceptron(data, labels, params={}, hook=None):
    # if T not in params, default to 100
    T = params.get('T', 100)

    # Your implementation here
    d, n = data.shape
    th = np.zeros((d, 1))
    th0 = np.zeros((1, 1))
    ths = np.zeros((d, 1))
    th0s = np.zeros((1, 1))

    for t in range(T):
        changed = False
        for i in range(n):
            if labels[0, i] * (np.dot(th.T, data[:, i : i+1]) + th0[0, 0]) <= 0:
                th = th + labels[0, i] * data[:, i : i+1]
                th0 = th0 + labels[0, i]
                changed = True
            ths = ths + th
            th0s = th0s + th0
    return ths/(n*T), th0s/(n*T)

In [17]:
averaged_perceptron(x, y, {'T': 100})

(array([[-2.014],
        [ 0.022]]),
 array([[-4.928]]))

In [ ]:
def eval_classifier(learner, data_train, labels_train, data_test, labels_test):
    

In [24]:
z = np.arange(8.0)
z

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [26]:
np.array_split(z, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [27]:
w = np.arange(9.0)
w

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [28]:
np.array_split(w, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [34]:
np.array_split(x, 3, axis=1)

[array([[-3, -1],
        [ 2,  1]]),
 array([[-1,  2],
        [-1,  2]]),
 array([[ 1],
        [-1]])]

In [35]:
np.concatenate((np.array_split(x, 3, axis=1)), axis=1)

array([[-3, -1, -1,  2,  1],
       [ 2,  1, -1,  2, -1]])

In [36]:
type(np.array_split(x, 3, axis=1))

list

In [37]:
D = np.array_split(x, 3, axis=1)

In [38]:
D[1]

array([[-1,  2],
       [-1,  2]])

In [39]:
np.concatenate((D[1:3]), axis=1)

array([[-1,  2,  1],
       [-1,  2, -1]])

In [46]:
np.concatenate((D[:1] + D[2:]), axis=1)

array([[-3, -1,  1],
       [ 2,  1, -1]])

In [41]:
D[:1]

[array([[-3, -1],
        [ 2,  1]])]

In [42]:
D[2:3]

[array([[ 1],
        [-1]])]

In [44]:
np.concatenate((D[0], D[2]), axis=1)

array([[-3, -1,  1],
       [ 2,  1, -1]])