In [1]:
import numpy as np

In [14]:
def perceptron(data, labels, params={}, hook=None):
    # if T not in params, default to 100
    T = params.get('T', 100)
    # Your implementation here
    d, n = data.shape
    th = np.zeros((d, 1))
    th0 = np.zeros((1, 1))
    mistakes = 0

    for t in range(T):
        changed = False
        for i in range(n):
            if labels[0, i] * (np.dot(th.T, data[:, i:i+1]) + th0[0, 0]) <= 0:
                th = th + labels[0, i] * data[:, i:i+1]
                mistakes += 1
                th0 = th0 + labels[0, i]
                changed = True
        if not changed:
            break
    return (th, th0)

In [13]:
data = np.array([[1, 1, 3, 3],[3, 1, 4, 2]])
data

array([[1, 1, 3, 3],
       [3, 1, 4, 2]])

In [14]:
labels = np.array([[-1, -1, 1, 1]])
labels

array([[-1, -1,  1,  1]])

In [17]:
perceptron(data, labels, {'T':100})

(array([[-2.]]), array([[7.]]))

In [15]:
th = np.array([[0, 1]]).T
th

array([[0],
       [1]])

In [16]:
th0 = -3
th0

-3

In [17]:
np.linalg.norm(th)

1.0

**multiplying a section of an array by a scalar**

In [114]:
new_data = np.copy(data)
new_data[:1, :] *= 0.001
new_data

array([[0.2, 0.8, 0.2, 0.8],
       [0.2, 0.2, 0.8, 0.8],
       [1. , 1. , 1. , 1. ]])

**finding margin**

In [18]:
gamma = ((np.dot(th.T, data) + th0)*labels)/np.linalg.norm(th)
gamma

array([[ 0.,  2.,  1., -1.]])

In [12]:
np.min(gamma)

-1.414213562373095

In [15]:
data.shape[1]

4

**finding radius**

In [117]:
radius = []
for i in range(new_data.shape[1]):
    radius.append(np.linalg.norm(new_data[:, i:i+1]))
radius

[1.0392304845413265, 1.2961481396815722, 1.2961481396815722, 1.50996688705415]

In [118]:
max(radius)/0.2683

5.627904908886135

**One Hot Encoding**

In [22]:
def one_hot(x, k):
    enc = np.zeros((k, 1))
    enc[x-1, 0] = 1
    return enc

In [23]:
one_hot(3, 7)

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [44]:
oneHot = np.zeros((6, data.shape[1]))
for i in range(data.shape[1]):
    oneHot[:, i:i+1] = one_hot(data[0, i], 6)

In [45]:
oneHot

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
th, th0 = perceptron(oneHot, labels, {'T':500})
th

array([[ 1.],
       [ 1.],
       [-2.],
       [-2.],
       [ 1.],
       [ 1.]])

In [50]:
th0

array([[0.]])

In [36]:
x = np.concatenate((one_hot(1, 6), one_hot(6,6)), axis=1)
x

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [38]:
(np.dot(th.T, x) + th0)

array([[0., 0.]])

In [41]:
np.dot(th.T, x) + th0

array([[0., 0.]])

In [52]:
order = [1, 10, 20, 30, 40, 50]
terms = []
for o in order:
    terms.append(((o+1)*(o+2))/2)
terms

[3.0, 66.0, 231.0, 496.0, 861.0, 1326.0]

In [5]:
idx_data = np.array(([[0.2, 0.8, 0.2, 0.8],
       [0.2, 0.2, 0.8, 0.8],
       [1. , 1. , 1. , 1. ]]))
idx_data

array([[0.2, 0.8, 0.2, 0.8],
       [0.2, 0.2, 0.8, 0.8],
       [1. , 1. , 1. , 1. ]])

In [13]:
idx = list(range(idx_data.shape[1]))
idx

[0, 1, 2, 3]

In [14]:
idx_data[:, idx]

array([[0.2, 0.8, 0.2, 0.8],
       [0.2, 0.2, 0.8, 0.8],
       [1. , 1. , 1. , 1. ]])

In [33]:
def col_average_features(x):
    """
    @param x (m,n) array with values in (0,1)
    @return (n,1) array where each entry is the average of a column
    """
    m, _ = x.shape
    col_sum = np.array([np.sum(x, axis=0)]).T
    return col_sum/m

In [34]:
def row_average_features(x):
    """
    @param x (m,n) array with values in (0,1)
    @return (m,1) array where each entry is the average of a row
    """
    _, n = x.shape
    row_sum = np.array([np.sum(x, axis=1)]).T
    return row_sum/n

In [35]:
np.array([np.sum(idx_data, axis=1)]).T

array([[2.],
       [2.],
       [4.]])

In [36]:
row_average_features(idx_data)

array([[0.5],
       [0.5],
       [1. ]])

In [29]:
_, n = idx_data.shape
n

4

In [32]:
int(5.9)

5

In [37]:
def top_bottom_features(x):
    """
    @param x (m,n) array with values in (0,1)
    @return (2,1) array where the first entry is the average of the
    top half of the image = rows 0 to floor(m/2) [exclusive]
    and the second entry is the average of the bottom half of the image
    = rows floor(m/2) [inclusive] to m
    """
    m, n = x.shape
    top_half = np.sum(x[0 : int(m/2)])/(int(m/2) * n)
    bottom_half = np.sum(x[int(m/2) : m])/ ((m - int(m/2)) * n)
    return np.array([[top_half, bottom_half]]).T
