In [1]:
import numpy as np

In [2]:
W_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
W0_1 = np.full((4, 1), -1)
W_2 = np.array([[1, 1, 1, 1], [-1, -1, -1, -1]]).T
W0_2 = np.array([[0, 2]]).T

X = np.array([[3, 4]]).T

z_1 = np.dot(W_1.T, X) + W0_1

In [3]:
z_1

array([[ 2],
       [ 3],
       [-4],
       [-5]])

In [4]:
z_1 > 0

array([[ True],
       [ True],
       [False],
       [False]])

In [6]:
z_1 * (z_1 > 0)

array([[2],
       [3],
       [0],
       [0]])