In [1]:
import numpy as np

In [23]:
A = np.random.randint(0, 10, size=(4, 3, 3))
A

array([[[3, 6, 9],
        [8, 6, 4],
        [7, 4, 1]],

       [[3, 6, 3],
        [3, 9, 1],
        [3, 1, 9]],

       [[5, 5, 8],
        [8, 3, 2],
        [2, 4, 7]],

       [[1, 9, 0],
        [1, 8, 8],
        [9, 3, 6]]])

In [24]:
A.shape

(4, 3, 3)

In [25]:
a = np.ones((3, 1))
a

array([[1.],
       [1.],
       [1.]])

In [26]:
np.dot(a.T, A)

array([[[18., 16., 14.],
        [ 9., 16., 13.],
        [15., 12., 17.],
        [11., 20., 14.]]])

In [27]:
A[1:2, :, :]

array([[[3, 6, 3],
        [3, 9, 1],
        [3, 1, 9]]])

In [15]:
C = np.zeros((4, 3, 3))
C

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
C[1:2, :, :] = A[1:2, :, :]

In [33]:
C

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[3., 6., 3.],
        [3., 9., 1.],
        [3., 1., 9.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
d = np.random.randint(0, 10, size=(3, 3))
d

array([[7, 7, 4],
       [9, 3, 9],
       [3, 4, 8]])

In [40]:
np.dot(d, A)

array([[[105, 100,  95],
        [ 54, 109,  64],
        [ 99,  72,  98],
        [ 50, 131,  80]],

       [[114, 108, 102],
        [ 63,  90, 111],
        [ 87,  90, 141],
        [ 93, 132,  78]],

       [[ 97,  74,  51],
        [ 45,  62,  85],
        [ 63,  59,  88],
        [ 79,  83,  80]]])

In [36]:
np.dot(np.array([[4, 6, 6]]), np.array([[3, 6, 9],
        [8, 6, 4],
        [7, 4, 1]]))

array([[102,  84,  66]])

In [41]:
np.dot(A, d)

array([[[102,  75, 138],
        [122,  90, 118],
        [ 88,  65,  72]],

       [[ 84,  51,  90],
        [105,  52, 101],
        [ 57,  60,  93]],

       [[104,  82, 129],
        [ 89,  73,  75],
        [ 71,  54, 100]],

       [[ 88,  34,  85],
        [103,  63, 140],
        [108,  96, 111]]])

In [42]:
e = np.random.randint(0, 10, size=(3,1))
e

array([[3],
       [6],
       [3]])

In [44]:
Ae = np.dot(A, e)
Ae

array([[[72],
        [72],
        [48]],

       [[54],
        [66],
        [42]],

       [[69],
        [48],
        [51]],

       [[57],
        [75],
        [63]]])

In [49]:
np.concatenate((Ae[0,:,:], Ae[1,:,:], Ae[2,:,:], Ae[3,:,:]), axis=1)

array([[72, 54, 69, 57],
       [72, 66, 48, 75],
       [48, 42, 51, 63]])